import { Router } from "express";
import feedRouter from "./feed";
import listingsRouter from "./listings";
import bookingsRouter from "./bookings";
import financingRouter from "./financing";
import searchRouter from "./search";
import leadsRouter from "./leads";
import savesRouter from "./saves";
import conversationsRouter from "./conversations";
import notificationsRouter from "./notifications";
import storiesRouter from "./stories";
import dealerRouter from "./dealer";
import meRouter from "./me";
import usersRouter from "./users";
import adsRouter from "./ads";
import uploadsRouter from "./uploads";
import walletRouter from "./wallet";
import subscriptionsRouter from "./subscriptions";
import paymentsRouter from "./payments";
import billingRouter from "./billing";
import reportsRouter from "./reports";
import supportRouter from "./support";
import adminRouter from "./admin";
import companiesRouter from "./companies";
import rfqsRouter from "./rfqs";
import sellersRouter from "./sellers";
import investmentsRouter from "./investments";
import globalSupplyRouter from "./global-supply";
import marketRouter from "./market";
import referenceRouter from "./reference";

const router = Router();

router.use("/me", meRouter);
router.use("/feed", feedRouter);
router.use("/listings", listingsRouter);
router.use("/bookings", bookingsRouter);
router.use("/financing", financingRouter);
router.use("/search", searchRouter);
router.use("/leads", leadsRouter);
router.use("/saves", savesRouter);
router.use("/conversations", conversationsRouter);
router.use("/notifications", notificationsRouter);
router.use("/stories", storiesRouter);
router.use("/dealer", dealerRouter);
router.use("/users", usersRouter);
router.use("/ads", adsRouter);
router.use("/uploads", uploadsRouter);
router.use("/wallet", walletRouter);
router.use("/subscriptions", subscriptionsRouter);
router.use("/payments", paymentsRouter);
router.use("/billing", billingRouter);
router.use("/reports", reportsRouter);
router.use("/support", supportRouter);
router.use("/admin", adminRouter);
router.use("/companies", companiesRouter);
router.use("/rfqs", rfqsRouter);
router.use("/sellers", sellersRouter);
router.use("/investments", investmentsRouter);
router.use("/global-supply", globalSupplyRouter);
router.use("/market", marketRouter);
router.use("/reference", referenceRouter);

export default router;
